# Build and deploy doxygen documention to GitHub Pages
sudo: false
dist: hirsute

# Blacklist
branches:
  only:
    - main

# Environment variables
env:
  global:
    - GH_REPO_REF: github.com/wolffshots/esp32-warm-water.git

# Install dependencies
before_install:
  - sudo apt-get update
  - sudo apt-get -y install doxygen doxygen-doc doxygen-latex doxygen-gui graphviz
# addons:
#   apt:
#     packages:
#       - doxygen
#       - doxygen-doc
#       - doxygen-latex
#       - doxygen-gui
#       - graphviz

# Build the docs
script:
  - cd doc
  - doxygen
  - lsb_release -a
  - doxygen -v

# Deploy using Travis-CI/GitHub Pages integration support
deploy:
  provider: pages
  skip-cleanup: true
  local-dir: doc/html
  github-token: $TRAVIS_TOKEN
  on:
    branch: main
  target-branch: gh-pages

