# Build and deploy doxygen documention to GitHub Pages
dist: focal

# Blacklist
branches:
  only:
    - main

# Environment variables
env:
  global:
    - GH_REPO_REF: github.com/wolffshots/esp32-warm-water.git

# Install dependencies
before_install:
  - sudo apt-get update
  - sudo apt install -y libclang1-9 libclang1-9 libllvm9
  - sudo apt install -y libclang-cpp9
  - wget -c https://doxygen.nl/files/doxygen-1.9.1.linux.bin.tar.gz -O - | tar -xz
  - cd doxygen-1.9.1/
  - sudo make install
  - cd ..
  - rm -fr doxygen-1.9.1 # crucial so it doesn't document itself

# addons:
#   apt:
#     packages:
#       - doxygen
#       - doxygen-doc
#       - doxygen-latex
#       - doxygen-gui
#       - graphviz

# Build the docs
script:
  - cd doc
  - doxygen
  - lsb_release -a
  - doxygen -v

# Deploy using Travis-CI/GitHub Pages integration support
deploy:
  provider: pages
  skip_cleanup: true
  local-dir: doc/html
  github-token: $TRAVIS_TOKEN
  on:
    branch: main
  target-branch: gh-pages

